require: rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - .batect/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 20
