dist: xenial

services:
  - docker

env:
  global:
    - BATECT_CACHE_TYPE=directory
    - BATECT_ENABLE_TELEMETRY=true

install: ./batect setup

script: ./travis/build.sh

cache:
  directories:
    - .batect/caches
