name: Pipeline

on: [push]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v3.0.11
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .batect/caches
          key: batect-caches-${{ hashFiles('Gemfile.lock') }}

      - name: Download dependencies
        run: ./batect setup

      - name: Lint
        run: ./batect lint

      - name: Run unit tests
        run: ./batect unitTest

      - name: Run integration tests
        run: ./batect integrationTest

      - name: Run journey tests
        run: ./batect journeyTest
